import { Metadata } from "next";
import Image from "next/image";

export const metadata: Metadata = {
	title: {
		default: "Create Next App",
		template: "%s | Next App",
	},
	description: "Generated by create next app",
};

const page = () => {
  return (
		<div>
			<Image
				src="https://res.cloudinary.com/dmmwi06zc/image/upload/v1737904303/ietcqg2pkdiekh7dooqa.jpg"
				alt="Keyboard"
				height="500"
				width="500"
			/>
		</div>
	);
}
export default page