import { Metadata } from "next";

export const metadata: Metadata = {
	title: {
		default: "Create Next App",
		template: "%s | Next App",
	},
	description: "Generated by create next app",
};

const page = () => {
  return (
    <div>Home Page</div>
  )
}
export default page